browse:
  credentials: [[ administrator, physicalstorage ]]

delete:
  credentials: [[ contributor, editor, administrator ]]
  is_secure: true

edit:
  credentials: [[ contributor, editor, administrator, translator, physicalstorage ]]
  is_secure: true

all:
  is_secure: true
