# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:

  # Upload limit (in gigabytes), possible values:
  #  Zero              => Uploads forbidden
  #  Negative integer  => Unlimited uploads
  #  Positive integer  => Number of gigabytes
  upload_limit: -1

  # Timeout for fetching digital objects from external services, in seconds
  download_timeout: 10

  # Use sfMemcacheCache if you want a distributed cache.
  # sfAPCCache works with both APC and APCu
  cache_engine: sfMemcacheCache
  cache_engine_param:
    host: 10.125.205.219
 #   port: 11211
    prefix: atom
    storeCacheInfo: true
    persistent: true

  # Enable read only mode. This setting may be overwritten
  # by and environment variable called "ATOM_READ_ONLY"
  read_only: false

  # Google Analitycs:
  # Set a GA property API key to track page view hits.
  # E.g.: UA-1234567-89
  google_analytics_api_key:
  # Set a GA custom dimension index numver (from the same property)
  # to track the repository name as a dimension in page view hits
  # of IOs, actors and repos index pages.
  # E.g.: 1
  google_analytics_institutions_dimension_index:

  # htmlpurifier is used in static pages, disabled by default
  htmlpurifier_enabled: false

  # Specify a CSV Transform script that can be automatically applied from
  # the CSV Import Page in AtoM
  # csv_transform_script_name: /full/path/to/transformscript
