# This file is part of Access to Memory (AtoM).
#
# Access to Memory (AtoM) is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Access to Memory (AtoM) is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# Access to Memory (AtoM); if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# REPOSITORY RECORD XML (2015) IMPORT FILTER MAPPINGS
#
# @subpackage object import
# @author Johan Pieterse <johan.pieterse@sita.co.za>
# @version svn: $Id:$

repository_object:
  XPath:  "//repository/repositoryinfo"
  Object:  Repository
  # define an axis for the parent object; if no node is matched here, the object is rooted if possible
  Parent:  "ancestor::repository | ancestor::repositoryheader | ancestor::repositoryid | ancestor::repositoryname"

  Methods:
    repositoryName:
      XPath:   "authorizedFormOfName"
      Method:  setRepositoryName

    repositoryDetail:
      XPath:   "repositorydetail"
      Method:  setDetail

    repositoryAliases:
      XPath:   "repositoryaliases"
      Method:  setAliases

    repositoryAddress:
      XPath:   "repositoryaddress"
      Method:  setAddress

    repositoryId:
      XPath:   "identifier"
      Method:  setIdentifier     
