# This file is part of Access to Memory (AtoM).
#
# Access to Memory (AtoM) is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Access to Memory (AtoM) is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# Access to Memory (AtoM); if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# EAD XML (2002) IMPORT FILTER MAPPINGS
#
# @package AccesstoMemory
# @subpackage object import
# @author MJ Suhonos <mj@suhonos.ca>
# @author Peter Van Garderen <peter@artefactual.com>
# @author Mike Cantelon <mike@artefactual.com>
# @version svn: $Id:$

user_object:
  XPath:  "//user/userinfo"
  Object:  User
  # define an axis for the parent object; if no node is matched here, the object is rooted if possible
  Parent:  "ancestor::user | ancestor::userheader | ancestor::userid | ancestor::username"

  Methods:
    userName:
      XPath:   "username"
      Method:  setuserName

    userEmail:
      XPath:   "useremail"
      Method:  setAddress

    userActive:
      XPath:   "useractive"
      Method:  setActive

    userId:
      XPath:   "userid"
      Method:  setId     
